title: DevOps Notes
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

aux_links:
  GitHub: https://github.com/natrajwadhai13/devops-notes

# Optional nav (if you're manually building one)
# nav:
#   - title: Git
#     children:
#       - title: Git Basics
#         url: /git/basics
